// Copyright 2018-present the CoreDHCP Authors. All rights reserved
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.

// Package docgen renders a plugin's package doc to the README.md that GitHub
// shows when someone opens the plugin's directory.
//
// The package doc is the only place a plugin is documented. GitHub does not
// render Go doc comments, so a link from the top-level README into
// plugins/<name>/ would otherwise land on a file listing. Rendering the same
// comment to a README keeps one source and two audiences.
package docgen

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/doc"
	"go/doc/comment"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

// Header is the first line of every generated README, so a reader who opens
// the file knows where the text came from.
const Header = "<!-- Code generated by coredhcp-docgen from the package doc; DO NOT EDIT. -->"

// readmeMode keeps the generated files at the same permissions
// coredhcp-generator writes its output with.
const readmeMode = 0o600

// README is one rendered file: the path it belongs at and the bytes that
// belong in it.
type README struct {
	// Path is the README.md inside the package directory.
	Path string
	// ImportPath is the package's import path, used as the title.
	ImportPath string
	// Content is the complete file, header line included.
	Content []byte
}

// Render walks the plugin packages under root and renders one README for
// each. Nothing is written; Write and Differing take it from here.
//
// A package directory is one below root/plugins holding at least one non-test
// .go file. The internal and testdata subtrees are left out: the first is not
// a plugin and the second holds fixtures that are not packages at all.
func Render(root string) ([]README, error) {
	module, err := modulePath(root)
	if err != nil {
		return nil, err
	}
	dirs, err := packageDirs(filepath.Join(root, "plugins"))
	if err != nil {
		return nil, err
	}
	readmes := make([]README, 0, len(dirs))
	for _, dir := range dirs {
		r, err := renderDir(root, dir, module)
		if err != nil {
			return nil, err
		}
		readmes = append(readmes, r)
	}
	return readmes, nil
}

// Write writes each rendered README to its path, replacing what is there.
func Write(readmes []README) error {
	for _, r := range readmes {
		if err := os.WriteFile(r.Path, r.Content, readmeMode); err != nil {
			return fmt.Errorf("cannot write %q: %w; check that the plugin directory exists and is writable", r.Path, err)
		}
	}
	return nil
}

// Differing returns the paths whose file on disk is not what Render produced,
// a missing file included. An empty result means every README is current.
func Differing(readmes []README) ([]string, error) {
	var stale []string
	for _, r := range readmes {
		current, err := isCurrent(r)
		if err != nil {
			return nil, err
		}
		if !current {
			stale = append(stale, r.Path)
		}
	}
	return stale, nil
}

func isCurrent(r README) (bool, error) {
	got, err := os.ReadFile(r.Path)
	switch {
	case errors.Is(err, fs.ErrNotExist):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("cannot read %q: %w; fix the permissions, or delete the file and regenerate", r.Path, err)
	}
	return bytes.Equal(got, r.Content), nil
}

// modulePath reads the module path out of root/go.mod. The README titles are
// import paths, and the module path is the only place the prefix is written
// down.
func modulePath(root string) (string, error) {
	name := filepath.Join(root, "go.mod")
	data, err := os.ReadFile(name)
	if err != nil {
		return "", fmt.Errorf("cannot read %q: %w; point -root at the repository root, the directory holding go.mod and plugins/", name, err)
	}
	for line := range strings.Lines(string(data)) {
		if path, ok := strings.CutPrefix(strings.TrimSpace(line), "module "); ok {
			return strings.TrimSpace(path), nil
		}
	}
	return "", fmt.Errorf("no module line in %q; coredhcp-docgen builds the README titles from the module path, so the file has to declare one", name)
}

// packageDirs returns the directories at or below root that hold Go source,
// sorted so two runs render the same set in the same order.
func packageDirs(root string) ([]string, error) {
	var dirs []string
	walk := func(path string, d fs.DirEntry, err error) error {
		switch {
		case err != nil:
			return err
		case !d.IsDir():
			return nil
		case path != root && skipDir(d.Name()):
			return fs.SkipDir
		}
		found, err := hasGoFiles(path)
		if found {
			dirs = append(dirs, path)
		}
		return err
	}
	if err := filepath.WalkDir(root, walk); err != nil {
		return nil, fmt.Errorf("cannot walk %q: %w; point -root at the repository root, the directory holding go.mod and plugins/", root, err)
	}
	slices.Sort(dirs)
	return dirs, nil
}

func skipDir(name string) bool {
	// The go tool ignores directories starting with '.' or '_' as well, so a
	// scratch copy left next to a plugin never turns into a README.
	return name == "internal" || name == "testdata" ||
		strings.HasPrefix(name, ".") || strings.HasPrefix(name, "_")
}

func hasGoFiles(dir string) (bool, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false, fmt.Errorf("cannot read directory %q: %w; fix the permissions, or move the directory out of plugins/", dir, err)
	}
	return slices.ContainsFunc(entries, isSourceFile), nil
}

func isSourceFile(e fs.DirEntry) bool {
	name := e.Name()
	return !e.IsDir() && strings.HasSuffix(name, ".go") && !strings.HasSuffix(name, "_test.go")
}

func renderDir(root, dir, module string) (README, error) {
	rel, err := filepath.Rel(root, dir)
	if err != nil {
		return README{}, fmt.Errorf("cannot place %q under %q: %w; give -root a path the plugin directories sit below", dir, root, err)
	}
	importPath := module + "/" + filepath.ToSlash(rel)
	pkg, err := parsePackage(dir, importPath)
	if err != nil {
		return README{}, err
	}
	return README{
		Path:       filepath.Join(dir, "README.md"),
		ImportPath: importPath,
		Content:    markdown(pkg, importPath),
	}, nil
}

func parsePackage(dir, importPath string) (*doc.Package, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("cannot read directory %q: %w; fix the permissions, or move the directory out of plugins/", dir, err)
	}
	fset := token.NewFileSet()
	var files []*ast.File
	for _, e := range entries {
		if !isSourceFile(e) {
			continue
		}
		name := filepath.Join(dir, e.Name())
		f, err := parser.ParseFile(fset, name, nil, parser.ParseComments|parser.SkipObjectResolution)
		if err != nil {
			return nil, fmt.Errorf("cannot parse %q: %w; fix the syntax error, coredhcp-docgen reads the doc comment straight from the source", name, err)
		}
		files = append(files, f)
	}
	return buildDoc(fset, files, importPath)
}

func buildDoc(fset *token.FileSet, files []*ast.File, importPath string) (*doc.Package, error) {
	pkg, err := doc.NewFromFiles(fset, files, importPath)
	if err != nil {
		return nil, fmt.Errorf("cannot assemble the package doc of %q: %w; the package has to parse as one package before its doc can be rendered", importPath, err)
	}
	return pkg, nil
}

func markdown(pkg *doc.Package, importPath string) []byte {
	printer := pkg.Printer()
	// A "# Section" in a doc comment prints as a top-level heading, which
	// would tie with the import path below. Level 2 puts the sections under
	// it instead.
	printer.HeadingLevel = 2
	// The printer appends a "{#hdr-Name}" anchor by default. GitHub has no
	// support for that extension and shows the braces as text.
	printer.HeadingID = func(*comment.Heading) string { return "" }

	var buf bytes.Buffer
	buf.WriteString(Header)
	buf.WriteString("\n\n# ")
	buf.WriteString(importPath)
	buf.WriteString("\n\n")
	buf.Write(printer.Markdown(pkg.Parser().Parse(pkg.Doc)))
	return append(bytes.TrimRight(buf.Bytes(), "\n"), '\n')
}
