name: Build

on: [push, pull_request]

permissions:
  contents: read

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coredhcp:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        go: ['1.25', '1.26']
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go }}
      - name: build coredhcp
        run: go build ./cmd/coredhcp
      - uses: actions/upload-artifact@v7
        with:
          name: coredhcp-${{ matrix.go }}
          path: coredhcp
          if-no-files-found: error
  coredhcp-generator:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        go: ['1.25', '1.26']
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go }}
      - name: build and check coredhcp-generator
        run: |
          set -exu
          cd cmd/coredhcp-generator
          go build
          builddir=$(./coredhcp-generator -f core-plugins.txt)
          cd "${builddir}"
          ls -l
          go mod init coredhcp
          go mod edit -replace "github.com/coredhcp/coredhcp=${GITHUB_WORKSPACE}"
          go mod tidy
          go build
          gofmt -w coredhcp.go
          diff -u coredhcp.go "${GITHUB_WORKSPACE}/cmd/coredhcp/main.go"
