name: Tests

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.24', '1.25', '1.26']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: run unit tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: report coverage to codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.txt
          disable_search: true
          flags: unittests
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.24', '1.25', '1.26']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: set up network namespaces
        run: ./test/integration/setup-netns.sh
      - name: run integration tests
        env:
          GOCOVERDIR: ${{ github.workspace }}/.cover
        run: |
          mkdir -p "$GOCOVERDIR"
          for d in test/integration/*/; do
              pushd "$d"
              go build -tags=integration -race -cover -coverpkg=github.com/coredhcp/coredhcp/... .
              testbin=$(basename "$d")
              test -x "${testbin}" || echo "::error file=${d}::missing binary for integration test ${d}"
              # only run it if it was built - i.e. if there are integ tests
              test -x "${testbin}" && sudo --preserve-env=GOCOVERDIR "./${testbin}"
              if [ $? -ne 0 ]; then
                echo "::error file=${d}::Execution of integration tests for ${d} failed"
              fi
              popd
          done
          go tool covdata textfmt -i="$GOCOVERDIR" -o=coverage.txt
      - name: report coverage to codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.txt
          disable_search: true
          flags: integtests
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
